-- Generated by scripts/gen-seed.ts — do not edit by hand.
-- Bootstrap catalog from src/test/fixtures/catalog.ts (the original Wolt
-- snapshot). After first apply the DATABASE is the source of truth — the
-- owner's edits live there; re-running this only restores missing rows.
-- Idempotent: upserts by id; owner-editable state (active) is preserved.

insert into public.categories (id, name, sort) values
  ('pizza', 'פיצות', 0),
  ('build', 'הרכבה עצמית', 1),
  ('pasta', 'פסטה', 2),
  ('sides', 'תוספות', 3),
  ('salads', 'סלטים', 4),
  ('drinks', 'שתייה', 5)
on conflict (id) do update set name = excluded.name, sort = excluded.sort;

insert into public.products
  (id, category_id, name, description, base_price, is_pizza, split_capable,
   included_toppings, variants, art, sort) values
  ('p_vino', 'pizza', 'וינו וינו', 'פפרוני, ירקות, בולגרית', 9500, true, true, 3, null, '["t_pepperoni","t_pepper","t_bulgarit"]'::jsonb, 0),
  ('p_shchitut', 'pizza', 'שחיתות', 'סלמי, פפרוני, אווז', 9500, true, true, 3, null, '["t_salami","t_pepperoni","t_goose"]'::jsonb, 1),
  ('p_monte', 'pizza', 'מונטקרלו', 'אווז, פטריות, בצל', 9500, true, true, 3, null, '["t_goose","t_mushroom","t_onion"]'::jsonb, 2),
  ('p_asia', 'pizza', 'אסיאתית', 'פפרוני, תירס, גמבה, אננס', 9500, true, true, 3, null, '["t_pepperoni","t_corn","t_pepper","t_pineapple"]'::jsonb, 3),
  ('p_romana', 'pizza', 'רומנה', 'פלפל, זיתים, סלמי', 9000, true, true, 3, null, '["t_pepper","t_olives","t_salami"]'::jsonb, 4),
  ('p_chicken', 'pizza', 'צ׳יקן', 'נתחי עוף וירקות', 10000, true, true, 3, null, '["t_chicken","t_pepper","t_corn"]'::jsonb, 5),
  ('p_mex', 'pizza', 'מקסיקנית', 'סלמי, חלפיניו, עגבניה, בולגרית', 9500, true, true, 3, null, '["t_salami","t_jalapeno","t_tomato","t_bulgarit"]'::jsonb, 6),
  ('p_pesto', 'pizza', 'פסטו', 'רוטב פסטו, בולגרית', 9500, true, true, 3, null, '["t_bulgarit","t_tomato"]'::jsonb, 7),
  ('p_alfredo', 'pizza', 'אלפרדו', 'רוטב אלפרדו, פטריות', 9500, true, true, 3, null, '["t_mushroom","t_extra_cheese"]'::jsonb, 8),
  ('p_veg', 'pizza', 'ירקות', 'פטריות, בצל, פלפל, זיתים', 9000, true, true, 3, null, '["t_mushroom","t_onion","t_pepper","t_olives"]'::jsonb, 9),
  ('p_vegan', 'pizza', '🌱 טבעונית', 'זיתים, פטריות, גמבה, בצל, תירס, עגבניות', 7000, true, true, 3, null, '["t_olives","t_mushroom","t_pepper","t_onion","t_corn","t_tomato"]'::jsonb, 10),
  ('b_personal', 'build', 'אישית בהרכבה', 'רוטב, גבינה צהובה', 3500, true, true, 3, null, '[]'::jsonb, 11),
  ('b_family', 'build', 'משפחתית בהרכבה', 'רוטב, גבינה צהובה', 6900, true, true, 3, null, '[]'::jsonb, 12),
  ('pa_penne', 'pasta', 'פנה', null, 7500, false, false, null, null, null, 13),
  ('pa_ravioli_cheese', 'pasta', 'רביולי גבינה', null, 7500, false, false, null, null, null, 14),
  ('pa_ravioli_potato', 'pasta', 'רביולי בטטה', null, 7500, false, false, null, null, null, 15),
  ('pa_fettuccine', 'pasta', 'פטוצ׳יני', null, 7500, false, false, null, null, null, 16),
  ('pa_spaghetti', 'pasta', 'ספגטי', null, 7500, false, false, null, null, null, 17),
  ('pa_tortellini', 'pasta', 'טורטליני פטריות', null, 7500, false, false, null, null, null, 18),
  ('pa_lasagna', 'pasta', 'לזניה', null, 8500, false, false, null, null, null, 19),
  ('s_chips', 'sides', 'צ׳יפס', null, 2000, false, false, null, '[{"id":"s_chips_s","label":"קטן","price":2000},{"id":"s_chips_l","label":"גדול","price":3000}]'::jsonb, null, 20),
  ('s_chips_alfredo', 'sides', 'צ׳יפס אלפרדו', null, 5000, false, false, null, null, null, 21),
  ('s_garlic', 'sides', 'לחם שום', null, 1500, false, false, null, '[{"id":"s_garlic_s","label":"קטן","price":1500},{"id":"s_garlic_l","label":"גדול","price":2500}]'::jsonb, null, 22),
  ('s_garlic_plus', 'sides', 'לחם שום משופר', 'צהובה ובולגרית', 3500, false, false, null, null, null, 23),
  ('s_wings', 'sides', 'כנפיים 10 יח׳', null, 8000, false, false, null, null, null, 24),
  ('s_schnitzel', 'sides', 'שניצלונים', null, 8500, false, false, null, null, null, 25),
  ('s_scaloppine', 'sides', 'סקלופיני עוף', null, 9000, false, false, null, null, null, 26),
  ('sl_chicken', 'salads', 'סלט עוף', null, 7500, false, false, null, null, null, 27),
  ('sl_greek', 'salads', 'סלט יווני', null, 5000, false, false, null, null, null, 28),
  ('sl_italian', 'salads', 'סלט איטלקי', null, 5000, false, false, null, null, null, 29),
  ('sl_tuna', 'salads', 'סלט טונה', null, 5000, false, false, null, null, null, 30),
  ('sl_chopped', 'salads', 'סלט ירקות קצוץ', null, 4000, false, false, null, null, null, 31),
  ('d_water', 'drinks', 'מים מינרליים 0.5', null, 800, false, false, null, null, null, 32),
  ('d_coke', 'drinks', 'קוקה קולה 0.33', null, 1000, false, false, null, null, null, 33),
  ('d_coke_zero', 'drinks', 'קולה זירו 0.33', null, 1000, false, false, null, null, null, 34),
  ('d_sprite', 'drinks', 'ספרייט 0.33', null, 1000, false, false, null, null, null, 35),
  ('d_fanta', 'drinks', 'פאנטה 0.33', null, 1000, false, false, null, null, null, 36),
  ('d_coke_big', 'drinks', 'קוקה קולה 1.5', null, 1500, false, false, null, null, null, 37),
  ('d_sprite_big', 'drinks', 'ספרייט 1.5', null, 1500, false, false, null, null, null, 38),
  ('d_fanta_big', 'drinks', 'פאנטה 1.5', null, 1500, false, false, null, null, null, 39)
on conflict (id) do update set
  category_id       = excluded.category_id,
  name              = excluded.name,
  description       = excluded.description,
  base_price        = excluded.base_price,
  is_pizza          = excluded.is_pizza,
  split_capable     = excluded.split_capable,
  included_toppings = excluded.included_toppings,
  variants          = excluded.variants,
  art               = excluded.art,
  sort              = excluded.sort,
  updated_at        = now();

insert into public.toppings (id, name, price) values
  ('t_mushroom', 'פטריות', 500),
  ('t_onion', 'בצל', 500),
  ('t_olives', 'זיתים', 500),
  ('t_corn', 'תירס', 500),
  ('t_pepper', 'גמבה', 500),
  ('t_jalapeno', 'חלפיניו', 500),
  ('t_pineapple', 'אננס', 500),
  ('t_tomato', 'עגבניות', 500),
  ('t_bulgarit', 'בולגרית', 700),
  ('t_pepperoni', 'פפרוני', 700),
  ('t_salami', 'סלמי', 700),
  ('t_goose', 'אווז', 700),
  ('t_tuna', 'טונה', 700),
  ('t_chicken', 'נתחי עוף', 900),
  ('t_extra_cheese', 'גבינה נוספת', 700)
on conflict (id) do update set name = excluded.name, price = excluded.price;

insert into public.bundles (id, name, items, price, active) values
  ('bnd_two_family', 'זוג משפחתיות', '[{"productId":"p_vino","qty":2}]'::jsonb, 16000, true),
  ('bnd_pizza_chips', 'משפחתית + צ׳יפס גדול', '[{"productId":"p_veg","qty":1},{"productId":"s_chips","qty":1}]'::jsonb, 10000, true)
on conflict (id) do nothing;
