// Generates supabase/seed.sql from the bundled catalog data, so the DB seed
// is always derived from the code and never hand-edited.
//
//   npx vite-node scripts/gen-seed.ts
//
// Apply by pasting supabase/seed.sql into the SQL Editor (or `supabase db reset`,
// which picks it up automatically). Re-running is safe: rows upsert by id, and
// owner-editable state (`active`) is left alone on existing rows.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundles, categories, products, toppings } from '../src/test/fixtures/catalog';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const opt = (s: string | undefined) => (s == null ? 'null' : q(s));
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const optJson = (v: unknown) => (v == null ? 'null' : json(v));

const categoryRows = categories.map((c, i) => `  (${q(c.id)}, ${q(c.name)}, ${i})`);

const productRows = products.map(
  (p, i) =>
    `  (${q(p.id)}, ${q(p.categoryId)}, ${q(p.name)}, ${opt(p.description)}, ${p.basePrice}, ` +
    `${!!p.isPizza}, ${!!p.splitCapable}, ${p.includedToppings ?? 'null'}, ` +
    `${optJson(p.variants)}, ${optJson(p.art)}, ${i})`,
);

const toppingRows = toppings.map((t) => `  (${q(t.id)}, ${q(t.name)}, ${t.price})`);

const bundleRows = bundles.map(
  (b) => `  (${q(b.id)}, ${q(b.name)}, ${json(b.items)}, ${b.price}, ${b.active})`,
);

const sql = `-- Generated by scripts/gen-seed.ts — do not edit by hand.
-- Bootstrap catalog from src/test/fixtures/catalog.ts (the original Wolt
-- snapshot). After first apply the DATABASE is the source of truth — the
-- owner's edits live there; re-running this only restores missing rows.
-- Idempotent: upserts by id; owner-editable state (active) is preserved.

insert into public.categories (id, name, sort) values
${categoryRows.join(',\n')}
on conflict (id) do update set name = excluded.name, sort = excluded.sort;

insert into public.products
  (id, category_id, name, description, base_price, is_pizza, split_capable,
   included_toppings, variants, art, sort) values
${productRows.join(',\n')}
on conflict (id) do update set
  category_id       = excluded.category_id,
  name              = excluded.name,
  description       = excluded.description,
  base_price        = excluded.base_price,
  is_pizza          = excluded.is_pizza,
  split_capable     = excluded.split_capable,
  included_toppings = excluded.included_toppings,
  variants          = excluded.variants,
  art               = excluded.art,
  sort              = excluded.sort,
  updated_at        = now();

insert into public.toppings (id, name, price) values
${toppingRows.join(',\n')}
on conflict (id) do update set name = excluded.name, price = excluded.price;

insert into public.bundles (id, name, items, price, active) values
${bundleRows.join(',\n')}
on conflict (id) do nothing;
`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql');
writeFileSync(out, sql);
// eslint-disable-next-line no-console
console.log(
  `wrote ${out}: ${categories.length} categories, ${products.length} products, ` +
    `${toppings.length} toppings, ${bundles.length} bundles`,
);
